### ISSUE TITLE
just tried running your example code and I get an error

### ISSUE THREAD

**Issue by lvsund** [XanderHorn/autoML#3]
code that was run:

library(autoEDA)
library(autoML)
library(data.table)
library(caret)

set.seed(1991)
full <- fread("/Volumes/NASPC/Downloads/kickstarter-projects/ks-projects-201801.csv",
              data.table = F,
              stringsAsFactors = F)

# Create binary target
full <- subset(full, full$state %in% c("failed","successful")) 

# Sample down for decrease in run time ~ 99k obs
full <- full[caret::createDataPartition(y = full$state, p = 0.3, list = F),]
# Quick tabular EDA
eda <- exploreData(x = full)

res <- autoML(train = full,
              target = "state",
              id = "ID",
              trainMode = "reduced",
              models = c("xgboost","randomforest"),
              modelInterpretability = F)

I get the following error:

autoPreProcess | Checking data 
autoPreProcess | Production code generated 
Error in `[.data.frame`(train, , target) : undefined columns selected
In addition: Warning message:
In if (id != "auto" & length(id) > 0) { :
  the condition has length > 1 and only the first element will be used

when i run against **my own data** I consistently get the 
Error in `[.data.frame`(train, , target) : undefined columns selected error

**Comment by XanderHorn** [comment]
This has been fixed, it was caused by a bug in the code. Thank you for reporting it, please download and re-install the package to run it again. 

Best
Xander
